version: "3.8"

services:
  mafia-server:
    image: 307946641609.dkr.ecr.ap-northeast-1.amazonaws.com/jingwook/mafia-server:latest
    container_name: mafia-server
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_R2DBC_URL: r2dbc:mysql://${RDS_ENDPOINT}:3306/mafia_game?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Seoul
      SPRING_R2DBC_USERNAME: ${RDS_USERNAME}
      SPRING_R2DBC_PASSWORD: ${RDS_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/mafia_game?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_ENDPOINT}
      SPRING_DATA_REDIS_PORT: 6379
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup mafia-server
    restart: unless-stopped
